services:
  api:
    build: .
    volumes:
      - "./settings.yaml:/code/settings.yaml:ro" # Read-only settings file
    depends_on:
      db:
        condition: service_started
    restart: always
    ports:
      - "8000:8000"
    env_file: .env

  db:
    # See more: https://registry.hub.docker.com/_/mongo
    image: "mongo:7.0"
    restart: always
    volumes:
      - "mongodb:/data/db"
    ports:
      - "27017:27017"
    env_file: .env # Set username and password in .env file

  minio:
    # See more: https://registry.hub.docker.com/minio/minio
    image: "minio/minio:RELEASE.2024-05-10T01-41-38Z"
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "minio:/data"
    command: server /data --console-address ":9001"
    env_file: .env # Set username and password in .env file

volumes:
  mongodb:
  minio:
