$schema: http://json-schema.org/draft-07/schema#
$defs:
  Environment:
    enum:
    - development
    - production
    title: Environment
    type: string
  FirstUser:
    additionalProperties: false
    properties:
      email:
        title: Email
        type: string
      name:
        title: Name
        type: string
    required:
    - email
    - name
    title: FirstUser
    type: object
  MinioSettings:
    additionalProperties: false
    properties:
      endpoint:
        default: 127.0.0.1:9000
        description: URL of the target service.
        title: Endpoint
        type: string
      secure:
        default: false
        description: Use https connection to the service.
        title: Secure
        type: boolean
      access_key:
        description: Access key (user ID) of a user account in the service.
        examples:
        - minioadmin
        title: Access Key
        type: string
      secret_key:
        description: Secret key (password) for the user account.
        examples:
        - password
        format: password
        title: Secret Key
        type: string
        writeOnly: true
    required:
    - access_key
    - secret_key
    title: MinioSettings
    type: object
  SMTP:
    additionalProperties: false
    properties:
      host:
        description: SMTP server host
        title: Host
        type: string
      port:
        default: 587
        description: SMTP server port
        title: Port
        type: integer
      username:
        description: SMTP server username
        title: Username
        type: string
      password:
        description: SMTP server password
        format: password
        title: Password
        type: string
        writeOnly: true
    required:
    - host
    - username
    - password
    title: SMTP
    type: object
additionalProperties: false
description: Settings for the application.
properties:
  $schema:
    default: null
    title: $Schema
    type: string
  environment:
    $ref: '#/$defs/Environment'
    default: development
    description: App environment flag
  app_root_path:
    default: ''
    description: Prefix for the API path (e.g. "/api/v0")
    title: App Root Path
    type: string
  session_secret_key:
    description: Secret key for session middleware
    format: password
    title: Session Secret Key
    type: string
    writeOnly: true
  database_uri:
    description: MongoDB database settings
    examples:
    - mongodb://mongoadmin:secret@localhost:27017/db?authSource=admin
    format: password
    title: Database Uri
    type: string
    writeOnly: true
  cors_allow_origins:
    default:
    - https://innohassle.ru
    - https://pre.innohassle.ru
    - http://localhost:3000
    description: 'Allowed origins for CORS: from which domains requests to the API
      are allowed'
    items:
      type: string
    title: Cors Allow Origins
    type: array
  smtp:
    anyOf:
    - $ref: '#/$defs/SMTP'
    - type: 'null'
    default: null
    description: SMTP settings
  minio:
    $ref: '#/$defs/MinioSettings'
  first_user:
    $ref: '#/$defs/FirstUser'
required:
- session_secret_key
- database_uri
- minio
- first_user
title: Settings
type: object
