$schema: "./settings.schema.yaml"
database_uri: mongodb://mongoadmin:secret@localhost:27017/db?authSource=admin # Database URL, "mongodb://mongoadmin:secret@db:27017/db?authSource=admin" inside the docker network
session_secret_key: "your-secret-key"
smtp:
  username: 108@innopolis.university
  password: sFmsdfjtg84885%%
  host: mail.innopolis.ru
  port: 587
