$schema: "./settings.schema.yaml"
database_uri: mongodb://localhost:27017/db?authSource=admin # Database URL, "mongodb://mongoadmin:secret@db:27017/db?authSource=admin" inside the docker network
session_secret_key: "YOUR_SECRET_KEY"
minio:
  endpoint: "127.0.0.1:9000"
  bucket: "candidate-iq"
  access_key: "YOUR_KEY"
  secret_key: "SECREY_KEY"
smtp:
  host: "YOUR_SMTP_HOST"
  username: "YOUR_SMTP_USERNAME"
  password: "YOUR_SMTP_PASSWORD"
